### ISSUE TITLE
你好，可不可以不用wepy实现点击单词请求api功能？

### ISSUE THREAD

**Issue by linleo10** [yshkk/shanbay-mina#5]
如题

**Comment by yshkk** [comment]
当然可以，这个跟框架无关吧。
我实现的思路是 在每个单词元素上通过data-* 绑定数据，在段落外面绑定click/tap事件，通过e.target.dataset就能拿到当前点击的单词，然后发请求就行了 参看https://github.com/yshkk/shanbay-mina/blob/593742b93aa84a7b190a96027399b251bf2701f0/src/pages/article.wpy#L107-L116

**Comment by linleo10** [comment]
谢谢





在2018年09月26日 11:32，yshkk 写道：

当然可以，这个跟框架无关吧。
我实现的思路是 在每个单词元素上通过data-* 绑定数据，在段落外面绑定click/tap事件，通过e.target.dataset就能拿到当前点击的单词，然后发请求就行了 参看https://github.com/yshkk/shanbay-mina/blob/593742b93aa84a7b190a96027399b251bf2701f0/src/pages/article.wpy#L107

**Comment by linleo10** [comment]
还有就是，我有个疑问，为什么您不直接用正则匹配每个单词呢




在2018年09月26日 19:56，linleo10 写道：
谢谢





在2018年09月26日 11:32，yshkk 写道：

当然可以，这个跟框架无关吧。
我实现的思路是 在每个单词元素上通过data-* 绑定数据，在段落外面绑定click/tap事件，通过e.target.dataset就能拿到当前点击的单词，然后发请求就行了 参看https://github.com/yshkk/shanbay-mina/blob/593742b93aa84a7b190a96027399b251bf2701f0/src/pages/article.wpy#L107

**Comment by yshkk** [comment]
能说具体点吗，怎么正则匹配

**Comment by linleo10** [comment]
word. replace(/([a-zA-Z]+)/g, '<text>$&</text>')




在2018年09月26日 20:41，yshkk 写道：

能说具体点吗，怎么正则匹配

**Comment by yshkk** [comment]
从api获取到的是一个句子，我手动split成一个个word的（短语情况特殊处理），在视图层将word用<text>标签渲染出来并绑定数据。
您说的正则的方法我没明白怎么使用，放到逻辑层处理，动态生成dom元素（小程序里可能不叫dom）吗
